In [5]:
import numpy as np

In [27]:
# Сумммирование значений
rng = np.random.default_rng(1)
s = rng.random(50)
print(s)

[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145 0.42332645
 0.82770259 0.40919914 0.54959369 0.02755911 0.75351311 0.53814331
 0.32973172 0.7884287  0.30319483 0.45349789 0.1340417  0.40311299
 0.20345524 0.26231334 0.75036467 0.28040876 0.48519097 0.9807372
 0.96165719 0.72478994 0.54122686 0.2768912  0.16065201 0.96992541
 0.51606859 0.11586561 0.62348976 0.77668311 0.6130033  0.9172977
 0.03959288 0.52858926 0.45933588 0.06234958 0.64132817 0.85263284
 0.59294102 0.26009745 0.83988152 0.50949588 0.51088888 0.75303021
 0.14792204 0.81962672]


In [29]:
print(sum(s))
print(np.sum(s))

25.985704258037675
25.98570425803768


In [35]:
a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])
print(np.sum(a))
print(np.sum(a, axis = 0)) # сумма по столбцам
print(np.sum(a, axis = 1)) # сумма по строкам

55
[ 7  9 11 13 15]
[15 40]


In [45]:
print(np.min(a))
print(np.min(a, axis = 0)) # мин по столбцам
print(a.min())
print(a.min(1))

1
[1 2 3 4 5]
1
[1 6]


In [57]:
# Транслирование

a = np.array([1,2,3])
b = np.array([5,5,5])

print(a+b)
print(a+5)

[6 7 8]
[6 7 8]


In [65]:
# Правила
# 1. Если размерности массивов отличаются, то форма массива с меньшей размерностью дополняется 1 с левой стороны
# 2. Если формы массивов не совпадают в каком-то измерении, то если у массива форма равна 1, то он "растягивается" до соответствующей формы
# 3. Если в каком-либо измерении размеры отличаются и ни в одном из них не равен 1, то генерируется ошибка

#a = np.array([[1,2,3],[4,5,6]])
#b = np.array([5])
#print(a.ndim, a.shape)

a = np.ones((2,3))
b = np.arange(3)

print(a)
print(b)

print(a.ndim, a.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
2 (2, 3)


In [79]:
# Маски - булевы массивы

x = np.array([1,2,3,4,5])
y = print (x < 3)

print (x[x<3])

[ True  True False False False]
[1 2]


In [95]:
# Векторизация индекса

x = np.array([0,1,2,3,4,5,6,7,8,9])
index = [1,5,7]
print (x[index])

index = [[0,1,7],[8,3,1]]
print (x[index])

[1 5 7]
[[0 1 7]
 [8 3 1]]


In [97]:
# Форма результата отражет форму массива индексов, а не форму исходного массива

x = np.arange(12).reshape((3,4))

print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [103]:
print(x[1, [2,0,1]])

[6 4 5]


In [109]:
x = [6,2,8,4,6,2,3,4,8,3,6,8,7]

print (sorted(x))
print (np.sort(x))

[2, 2, 3, 3, 4, 4, 6, 6, 6, 7, 8, 8, 8]
[2 2 3 3 4 4 6 6 6 7 8 8 8]


In [111]:
# Структурированный массив

data = np.zeros(4, dtype = {
    'names':(
        'name','age'
    ),
    'formats':(
        'U10','i4'
    )
})
print (data.dtype)

[('name', '<U10'), ('age', '<i4')]


In [115]:
name = ['name1','name2','name3','name4']
age = [10,20,30,40]
data['name'] = name;
data['age'] = age;

print(data)

[('name1', 10) ('name2', 20) ('name3', 30) ('name4', 40)]


In [117]:
print (data['age'] > 20)

[False False  True  True]


In [119]:
print (data[data['age'] > 20]['name'])

['name3' 'name4']
