In [2]:
import numpy as np
import pandas as pd

In [4]:
# Мультииндекс (индекс с размерностью >2)

In [14]:
index = [
    ('city_1',2011),
    ('city_1',2012),
    ('city_2',2011),
    ('city_2',2012),
    ('city_3',2011),
    ('city_3',2012),
]

population = [
    101,
    201,
    102,
    202,
    103,
    203
]
pop = pd.Series(population, index=index)
print (pop)

(city_1, 2011)    101
(city_1, 2012)    201
(city_2, 2011)    102
(city_2, 2012)    202
(city_3, 2011)    103
(city_3, 2012)    203
dtype: int64


In [16]:
index = pd.MultiIndex.from_tuples(index)
pop = pop.reindex(index)
print(pop)

city_1  2011    101
        2012    201
city_2  2011    102
        2012    202
city_3  2011    103
        2012    203
dtype: int64


In [50]:
print (pop[:, 2012])

city_1    201
city_2    202
city_3    203
dtype: int64


In [38]:
pop_df = pop.unstack()
print (pop_df)

        2011  2012
city_1   101   201
city_2   102   202
city_3   103   203


In [40]:
pop_df = pop_df.stack()
print (pop_df)

city_1  2011    101
        2012    201
city_2  2011    102
        2012    202
city_3  2011    103
        2012    203
dtype: int64


In [104]:
index = [
    ('city_1',2011,1),
    ('city_1',2011,2),
    ('city_1',2012,1),
    ('city_1',2012,2),
    ('city_2',2013,1),
    ('city_2',2013,2),
    ('city_2',2014,1),
    ('city_2',2014,2),
    ('city_3',2015,1),
    ('city_3',2015,2),
    ('city_3',2016,1),
    ('city_3',2016,2),
]

population = [
    101,
    201,
    102,
    202,
    103,
    203,
    104,
    204,
    105,
    205,
    106,
    206
]

pop = pd.Series(population, index=index)
print (pop)

(city_1, 2011, 1)    101
(city_1, 2011, 2)    201
(city_1, 2012, 1)    102
(city_1, 2012, 2)    202
(city_2, 2013, 1)    103
(city_2, 2013, 2)    203
(city_2, 2014, 1)    104
(city_2, 2014, 2)    204
(city_3, 2015, 1)    105
(city_3, 2015, 2)    205
(city_3, 2016, 1)    106
(city_3, 2016, 2)    206
dtype: int64


In [106]:
index = pd.MultiIndex.from_tuples(index)
pop = pop.reindex(index)
print(pop)

city_1  2011  1    101
              2    201
        2012  1    102
              2    202
city_2  2013  1    103
              2    203
        2014  1    104
              2    204
city_3  2015  1    105
              2    205
        2016  1    106
              2    206
dtype: int64


In [108]:
pop_df = pop.unstack()
print (pop_df)

               1    2
city_1 2011  101  201
       2012  102  202
city_2 2013  103  203
       2014  104  204
city_3 2015  105  205
       2016  106  206


In [120]:
# Способы создания мультииндексов

# - список массивов, задющих значение индекса на каждом уровне
i1 = pd.MultiIndex.from_arrays(
    [
        ['a','a','b','b'],
        [1,2,1,2]
    ]
)
print(i1)

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )


In [122]:
# - список кортежей, задающих значение индекса в каждой точке
i2 = pd.MultiIndex.from_tuples(
    [
        ('a',1),
        ('a',2),
        ('b',1),
        ('b',2),
    ]
)
print(i2)

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )


In [124]:
# - декартового произведение
i3 = pd.MultiIndex.from_product(
    [
        ['a','b'],
        [1,2]
    ]
)
print(i3)

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )


In [128]:
# - описание внутренного представления с помощью "levels" и "codes"
i4 = pd.MultiIndex(
    levels = [
        ['a','b','c'],
        [1,2]
    ],
    codes = [
        [0,0,1,1,2,2], # a a b b c c 
        [0,1,0,1,0,1]  # 1 2 1 2 1 2 
    ]
)
print(i4)

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )


In [300]:
# Уровням можно задавать названия
data = { 
    ('city_1', 2010): 100,
    ('city_1', 2020): 200,
    ('city_2', 2010): 1001,
    ('city_2', 2020): 2001
}

s = pd.Series(data)
print (s)

city_1  2010     100
        2020     200
city_2  2010    1001
        2020    2001
dtype: int64


In [302]:
s.index.names = ['city','year'] # имена уровней
print (s)

city    year
city_1  2010     100
        2020     200
city_2  2010    1001
        2020    2001
dtype: int64


In [459]:
# продолжение

index = pd.MultiIndex.from_product(
    [
        ['city_1','city_2'],
        [2010,2020]
    ]
)
print(index)

columns = pd.MultiIndex.from_product(
    [
        ['person_1','person_2','person_3'],
        ['job_1','job_2']
    ],
    names = ['worker', 'job']
)
print(columns)

MultiIndex([('city_1', 2010),
            ('city_1', 2020),
            ('city_2', 2010),
            ('city_2', 2020)],
           )
MultiIndex([('person_1', 'job_1'),
            ('person_1', 'job_2'),
            ('person_2', 'job_1'),
            ('person_2', 'job_2'),
            ('person_3', 'job_1'),
            ('person_3', 'job_2')],
           names=['worker', 'job'])


In [437]:
rng = np.random.default_rng(1)
data = rng.random((4,6))
print (data)

[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145 0.42332645]
 [0.82770259 0.40919914 0.54959369 0.02755911 0.75351311 0.53814331]
 [0.32973172 0.7884287  0.30319483 0.45349789 0.1340417  0.40311299]
 [0.20345524 0.26231334 0.75036467 0.28040876 0.48519097 0.9807372 ]]


In [439]:
data_df = pd.DataFrame(data, index = index, columns = columns)
print (data_df)

worker       person_1            person_2            person_3          
job             job_1     job_2     job_1     job_2     job_1     job_2
city_1 2010  0.511822  0.950464  0.144160  0.948649  0.311831  0.423326
       2020  0.827703  0.409199  0.549594  0.027559  0.753513  0.538143
city_2 2010  0.329732  0.788429  0.303195  0.453498  0.134042  0.403113
       2020  0.203455  0.262313  0.750365  0.280409  0.485191  0.980737


In [441]:
# 2 задание
print (data_df.loc[(slice(None),2020), :]) 
# slice(None) - используется для выбора всех значений на первом уровне (city), 
#               а '2020' выбирает только данные для указанной работы
#               ":" - все столбцы

worker       person_1            person_2            person_3          
job             job_1     job_2     job_1     job_2     job_1     job_2
city_1 2020  0.827703  0.409199  0.549594  0.027559  0.753513  0.538143
city_2 2020  0.203455  0.262313  0.750365  0.280409  0.485191  0.980737


In [443]:
print (data_df.loc[:, (slice(None), 'job_1')]) # slice(None) - все воркеры
#               ":" - все строки

worker       person_1  person_2  person_3
job             job_1     job_1     job_1
city_1 2010  0.511822  0.144160  0.311831
       2020  0.827703  0.549594  0.753513
city_2 2010  0.329732  0.303195  0.134042
       2020  0.203455  0.750365  0.485191


In [457]:
print (data_df.loc[('city_1',slice(None)), (slice(None), 'job_2')])

worker       person_1  person_2  person_3
job             job_2     job_2     job_2
city_1 2010  0.950464  0.948649  0.423326
       2020  0.409199  0.027559  0.538143


In [447]:
# 3 задание
print (data_df.loc[:, (['person_1','person_3'], slice(None))])

worker       person_1            person_3          
job             job_1     job_2     job_1     job_2
city_1 2010  0.511822  0.950464  0.311831  0.423326
       2020  0.827703  0.409199  0.753513  0.538143
city_2 2010  0.329732  0.788429  0.134042  0.403113
       2020  0.203455  0.262313  0.485191  0.980737


In [453]:
# с использованием срезов IndexSlice
idx = pd.IndexSlice
print (data_df.loc[idx['city_1', :], idx[['person_1', 'person_2'], :]])

worker       person_1            person_2          
job             job_1     job_2     job_1     job_2
city_1 2010  0.511822  0.950464  0.144160  0.948649
       2020  0.827703  0.409199  0.549594  0.027559


In [ ]:
# Индексация и срезы (по мультииндексу)

In [389]:
data = {
    ('city_1', 2010): 100,
    ('city_1', 2020): 200,
    ('city_2', 2010): 1001,
    ('city_2', 2020): 2001
}

s = pd.Series(data)
s.index.names = ['city', 'year'] # название индекса
print (s)

city    year
city_1  2010     100
        2020     200
city_2  2010    1001
        2020    2001
dtype: int64


In [395]:
print (s['city_1'])
print (s['city_1', 2010])

year
2010    100
2020    200
dtype: int64
100


In [479]:
# переиндексация
print (pop)

city_1  2011  1    101
              2    201
        2012  1    102
              2    202
city_2  2013  1    103
              2    203
        2014  1    104
              2    204
city_3  2015  1    105
              2    205
        2016  1    106
              2    206
dtype: int64


In [481]:
print (pop.unstack())

               1    2
city_1 2011  101  201
       2012  102  202
city_2 2013  103  203
       2014  104  204
city_3 2015  105  205
       2016  106  206


In [487]:
print (pop.unstack(level = 0))

        city_1  city_2  city_3
2011 1   101.0     NaN     NaN
     2   201.0     NaN     NaN
2012 1   102.0     NaN     NaN
     2   202.0     NaN     NaN
2013 1     NaN   103.0     NaN
     2     NaN   203.0     NaN
2014 1     NaN   104.0     NaN
     2     NaN   204.0     NaN
2015 1     NaN     NaN   105.0
     2     NaN     NaN   205.0
2016 1     NaN     NaN   106.0
     2     NaN     NaN   206.0


In [489]:
print (pop.unstack(level = 1))

           2011   2012   2013   2014   2015   2016
city_1 1  101.0  102.0    NaN    NaN    NaN    NaN
       2  201.0  202.0    NaN    NaN    NaN    NaN
city_2 1    NaN    NaN  103.0  104.0    NaN    NaN
       2    NaN    NaN  203.0  204.0    NaN    NaN
city_3 1    NaN    NaN    NaN    NaN  105.0  106.0
       2    NaN    NaN    NaN    NaN  205.0  206.0


In [491]:
# Pandas concat

In [509]:
ser1 = pd.Series(['a','b','c'], index = [1,2,3])
ser2 = pd.Series(['d','e','f'], index = [1,2,3])
print (pd.concat([ser1, ser2]))

1    a
2    b
3    c
1    d
2    e
6    f
dtype: object


In [507]:
print (pd.concat([ser1, ser2], axis=0, join='outer'))

1    a
2    b
3    c
1    d
2    e
6    f
dtype: object


In [515]:
ser1 = pd.Series(['a','b','c'], index = [2,3,4])
ser2 = pd.Series(['d','e','f'], index = [3,4,5])
print (pd.concat([ser1, ser2], axis=0, join='inner'))

2    a
3    b
4    c
3    d
4    e
5    f
dtype: object


In [6]:
# Задание 4
ser1 = pd.Series(['apple', 'banana', 'cherry'], index=[1, 2, 3])
ser2 = pd.Series(['banana', 'cherry', 'date'], index=[3, 4, 5])

outer_result = pd.concat([ser1, ser2], join='outer')
print(outer_result)

inner_result = pd.concat([ser1, ser2], join='inner')
print(inner_result)

Outer Join Result:
1    a
2    b
3    c
3    b
4    c
5    d
dtype: object

Inner Join Result:
1    a
2    b
3    c
3    b
4    c
5    d
dtype: object
