In [19]:
import numpy as np

In [118]:
import sys
import array
a = array.array('i', [2,3])
print(sys.getsizeof(a))
print (type(a))
print(a)

88
<class 'array.array'>
array('i', [2, 3])


In [68]:
array = np.linspace(0, 1, 5)
print(array)

[0.   0.25 0.5  0.75 1.  ]


In [70]:
array_gauss = np.random.uniform(0, 1, 5)
print(array_gauss)

[0.58965083 0.71105105 0.99866984 0.69150453 0.87825838]


In [72]:
array_normal = np.random.normal(0, 1, 5)
print(array_normal)

[ 1.29556057 -0.12946221 -0.9139434  -0.66265407 -0.28310029]


In [74]:
array_random = np.random.randint(0, 10, 5)
print(array_random)

[3 9 7 5 3]


In [98]:
arr = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
arr

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [100]:
print(arr[:2,:3])

[[1 2 3]
 [4 5 6]]


In [102]:
print(arr[:,1])

[2 5 8]


In [104]:
print(arr[::-1,::-1])

[[10  9  8  7]
 [ 7  6  5  4]
 [ 4  3  2  1]]


In [106]:
print(arr[:,1])

[2 5 8]


In [108]:
print(arr[2,:])

[ 7  8  9 10]


In [154]:
a = np.array([1,2,3,4,5])
b = a[:3].copy()
b[0] = 100
print(c)
print(a)

[100   2   3]
[1 2 3 4 5]


In [172]:
a = np.array([1,2,3,4,5])
stolb = a[:, np.newaxis]
stroka = a[np.newaxis, :]
print(a)
print(stolb)
print(stroka)

[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[1 2 3 4 5]]


In [210]:
a = np.array([[1,2,3],[4,5,6],[7,0,0]])
b = np.array([[0,8,0],[7,8,9],[0,3,1]])
c = np.dstack([a,b])
print(c)

[[[1 0]
  [2 8]
  [3 0]]

 [[4 7]
  [5 8]
  [6 9]]

 [[7 0]
  [0 3]
  [0 1]]]


In [212]:
x = np.arange(1,11)
print(np.multiply.outer(x,x))

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [214]:
x = np.array([1, 2, 3, 4, 5, 6])
print(x)
print(np.split(x, 3))
y = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(np.vsplit(y, 3))
print(np.hsplit(y, 3))
print(np.dsplit(c, 2))

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
[array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [0],
        [0]]]), array([[[0],
        [8],
        [0]],

       [[7],
        [8],
        [9]],

       [[0],
        [3],
        [1]]])]


In [240]:
x = np.array([1,2,3])
print(x*2)
print(abs(x-10))
print(x%2)
print(x//2)
print(x**2)
print(np.sin(x))
print(np.log(x))
print(np.exp(x))

[2 4 6]
[9 8 7]
[1 0 1]
[0 1 1]
[1 4 9]
[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]
