In [8]:
import numpy as np
import pandas as pd

In [10]:
# Pandas: Series, DataFrame, Index

In [20]:
# Pandas Series
data = pd.Series([0,5,10,15])
print (data)

print (data.values)
print (data.index)

0     0
1     5
2    10
3    15
dtype: int64
[ 0  5 10 15]
RangeIndex(start=0, stop=4, step=1)


In [36]:
print (data[2])
print (data[2:4])

10
2    10
3    15
dtype: int64


In [70]:
data = pd.Series([1,2,'wasd',4], index = ['a','b','c',7])
#print (data)
#print (data['a'])
#print (data['b':'d'])
#print (data[7])
print (data['b':7])

b       2
c    wasd
7       4
dtype: object


In [76]:
population_dict = {
    'city_1' : 101,
    'city_2' : 102,
    'city_3' : 103
}

population = pd.Series(population_dict)
print(population)

city_1    101
city_2    102
city_3    103
dtype: int64


In [78]:
# DataFrame - двумерный массив с явно определенными индексами. 
# Последовательность согласованных объектов Series

In [80]:
population_dict = {
    'city_1' : 101,
    'city_2' : 102,
    'city_3' : 103
}

area_dict = {
    'city_1' : 200,
    'city_2' : 300,
    'city_3' : 400
}
population = pd.Series(population_dict)
area = pd.Series(area_dict)

print(population)
print(area)

city_1    101
city_2    102
city_3    103
dtype: int64
city_1    200
city_2    300
city_3    400
dtype: int64


In [92]:
states = pd.DataFrame({
    'population1': population,
    'area1': area
})
print (states)
print (states.values)
print (states.index)
print (states.columns)

        population1  area1
city_1          101    200
city_2          102    300
city_3          103    400
[[101 200]
 [102 300]
 [103 400]]
Index(['city_1', 'city_2', 'city_3'], dtype='object')
Index(['population1', 'area1'], dtype='object')


In [96]:
print (states['population1'])

city_1    101
city_2    102
city_3    103
Name: population1, dtype: int64


In [98]:
# Index - способ организации ссылки на данные объектов Series и DataFrame.
# Index неизменяем упорядочен, является мультимножеством (могут быть повторяющиеся значения)

In [100]:
indA = pd.Index([1,2,3,4,5])
indB = pd.Index([2,3,4,5,6])
print(indA.intersection(indB)) # повторные элементы

Index([2, 3, 4, 5], dtype='int64')


In [110]:
# Выборка данных из Series
data = pd.Series([1,2,3,4], index = ['a','b','c','d'])
print ('a' in data)
print (data.keys())
print (list(data.items()))

data['a'] = 999
print (data)

True
Index(['a', 'b', 'c', 'd'], dtype='object')
[('a', 1), ('b', 2), ('c', 3), ('d', 4)]
a    999
b      2
c      3
d      4
dtype: int64


In [118]:
data = pd.Series([1,2,3,4], index = [1,3,7,'d'])
print (data[3])
print (data.loc[3])
print (data.iloc[3])

2
2
4


In [124]:
# Выборка данных из DataFrame

population_dict = {
    'city_1' : 101,
    'city_2' : 102,
    'city_3' : 103
}
area_dict = {
    'city_1' : 200,
    'city_2' : 300,
    'city_3' : 400,
    'city_4' : 500
}

population = pd.Series(population_dict)
area = pd.Series(area_dict)

data = pd.DataFrame({
    'population1': population,
    'area1': area
})

print (data.T)

             city_1  city_2  city_3  city_4
population1   101.0   102.0   103.0     NaN
area1         200.0   300.0   400.0   500.0


In [128]:
# Способы хранения отсутствующих значений
# - индикаторы NaN (not a number)
# - null

vall =np.array([1,2,3,4,5])
print (vall.sum())

15


In [136]:
vall =np.array([1,2,np.nan,4,5])
print (vall.sum())
print (np.nansum(vall))


nan
12.0


In [142]:
x = pd.Series(range(10), dtype=int)
x[0] = np.nan
x[1] = None
print(x)

0    NaN
1    NaN
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64


In [148]:
x = pd.Series(['a','b','c'])
x[0] = np.nan
x[1] = None
print(x)

0     NaN
1    None
2       c
dtype: object


In [170]:
x = pd.Series([np.nan, 1,65,2, None, np.nan], dtype='Int32')
print(x)
print(x.isnull())

0    <NA>
1       1
2      65
3       2
4    <NA>
5    <NA>
dtype: Int32
0     True
1    False
2    False
3    False
4     True
5     True
dtype: bool


In [214]:
print(x.dropna())

1     1
2    65
3     2
dtype: Int32


In [194]:
data['new'] = data['population1']
print (data)

        population1  area1    new
city_1        101.0    200  101.0
city_2        102.0    300  102.0
city_3        103.0    400  103.0
city_4          NaN    500    NaN


In [204]:
rng = np.random.default_rng()

A = rng.integers(0,10, (3,4))
print (A)

[[9 6 1 0]
 [0 9 3 4]
 [9 4 3 5]]


In [210]:
df = pd.DataFrame(A, columns=['a','b','c','d'])
print (df) 

   a  b  c  d
0  9  6  1  0
1  0  9  3  4
2  9  4  3  5


In [212]:
print (df - A[0]) # транслирование

   a  b  c  d
0  0  0  0  0
1 -9  3  2  4
2  0 -2  2  5
